version: '3.8'
services:
  web:
    build: ./webapp
    user: ${UID}:${GID}
    # command: sh -c "while true; do nc -lk -v -p 8000 ;done"
    command: gunicorn bugfinder.wsgi --workers=3 --bind 0.0.0.0:8000
    volumes:
      - type: bind
        source: ./data
        target: /usr/src/app/data
      - ./webapp/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    # user: ${UID}:${GID}
    volumes:
      - static_volume:/www/data/staticfiles
      - ${CERT_FILE}:/etc/nginx/certs/cert.pem
      - ${CERT_KEY}:/etc/nginx/certs/cert.key
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - web

volumes:
  static_volume:

     
