# Generated by Django 4.2 on 2023-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("function_name", models.TextField(blank=True, null=True)),
                ("function_basic_block_count", models.TextField(blank=True, null=True)),
                ("function_size", models.TextField(blank=True, null=True)),
                ("function_arch", models.TextField(blank=True, null=True)),
                ("function_platform", models.TextField(blank=True, null=True)),
                ("sample_hash", models.TextField(blank=True, null=True)),
                ("sample_name", models.TextField(blank=True, null=True)),
                ("dewolf_options", models.TextField(blank=True, null=True)),
                ("dewolf_current_commit", models.TextField(blank=True, null=True)),
                ("binaryninja_version", models.TextField(blank=True, null=True)),
                ("dewolf_exception", models.TextField(blank=True, null=True)),
                ("dewolf_traceback", models.TextField(blank=True, null=True)),
                ("dewolf_decompilation_time", models.TextField(blank=True, null=True)),
                ("dewolf_undecorated_code", models.TextField(blank=True, null=True)),
                ("is_successful", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "dewolf",
                "managed": False,
            },
        ),
    ]
