# Generated by Django 4.2 on 2023-06-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DewolfError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.TextField(blank=True, null=True)),
                ('function_basic_block_count', models.IntegerField(blank=True, null=True)),
                ('function_size', models.IntegerField(blank=True, null=True)),
                ('function_arch', models.TextField(blank=True, null=True)),
                ('function_platform', models.TextField(blank=True, null=True)),
                ('sample_hash', models.TextField(blank=True, null=True)),
                ('sample_name', models.TextField(blank=True, null=True)),
                ('dewolf_options', models.TextField(blank=True, null=True)),
                ('dewolf_current_commit', models.TextField(blank=True, null=True)),
                ('binaryninja_version', models.TextField(blank=True, null=True)),
                ('dewolf_exception', models.TextField(blank=True, null=True)),
                ('dewolf_traceback', models.TextField(blank=True, null=True)),
                ('dewolf_decompilation_time', models.IntegerField(blank=True, null=True)),
                ('dewolf_undecorated_code', models.TextField(blank=True, null=True)),
                ('is_successful', models.BooleanField(blank=True, null=True)),
                ('error_file_path', models.TextField(blank=True, null=True)),
                ('error_line', models.TextField(blank=True, null=True)),
                ('case_group', models.TextField(blank=True, null=True)),
                ('errors_per_group_count_pre_filter', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dewolf_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GitHubIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_group', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('html_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='sample',
            table='samples',
        ),
    ]
